fint:
  application-id: fint-kontroll-orgunit-catalog
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user
  kontroll:
    orgunit-catalog:
      pagesize: 9999
    # Override default OPA url for use locally
    opa:
      url: http://localhost:8181/v1/data/accessmanagement
    authorization:
      authorized-role: 'https://role-catalog.vigoiks.no/vigo/kontroll/user'
      authorized-admin-role: 'https://role-catalog.vigoiks.no/vigo/kontroll/admin'
      authorized-org-id: 'vigo.no'
spring:
  mvc:
    servlet:
      path: /
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  profiles:
    include:
      - kafka
      - db
logging:
  level:
    root: INFO
    org.apache.kafka: INFO

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /api/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
