fint:
  org-id: fintlabs.no
  flyt:
    resource-gateway:
      authorization:
        enable: true
  client:
    base-url: https://beta.felleskomponent.no
  application-id: fint-kontroll-orgunit-catalog
  kontroll:
    orgunit-catalog:
      pagesize: 50
      load-test-orgunits: true
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      schema: public
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
