fint:
  org-id: fintlabs.no
  flyt:
    resource-gateway:
      authorization:
        enable: true
  client:
    base-url: https://beta.felleskomponent.no
  application-id: fint-kontroll-orgunit-catalog
  kafka:
    default-replicas: 1
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}
  kontroll:
    orgunit-catalog:
      pagesize: 9999
spring:
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}
  datasource:
    hikari:
      schema: orgunits
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration/
    lock-retry-count: 300
    #baselineOnMigrate: true
server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /api/api-docs
