fint:
  application-id: fint-kontroll-orgunit-catalog
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user
  kontroll:
    orgunit-catalog:
      pagesize: 50
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  profiles:
    include:
      - kafka
      - db
  data:
    rest:
      base-path: /beta/fintlabs-no
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
