fint:
  application-id: fint-kontroll-orgunit-catalog
  kafka:
    default-replicas: 1
    topic:
      org-id: ${fint.org-id}
      domain-context: kontroll
    application-id: ${fint.application-id}
  client:
    password: ''
    username: ''
    base-url: https://beta.felleskomponent.no
    registration-id: fint
  kontroll:
    orgunit-catalog:
      pagesize: 50
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  profiles:
    include:
      - kafka
      - db
logging:
  level:
    root: INFO
    org.apache.kafka: INFO
    org.hibernate.SQL: INFO