INSERT INTO public.org_unit VALUES (801, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1022]', 'OKO System- og fellestjenester', '35', '30', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/35', 'OKO SYSFEL');
INSERT INTO public.org_unit VALUES (802, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1039]', 'DIGIT Lokasjonssupport sone Fylkeshus', '1178', '50', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/1178', 'DIGIT FYLKESHUS');
INSERT INTO public.org_unit VALUES (803, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1402]', 'INFRA Avdeling for mobilitet og samfunn', '85', '8', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/85', 'INFRA MOBSAM');
INSERT INTO public.org_unit VALUES (804, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1037]', 'DIGIT Lokasjonssupport', '50', '37', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/50', 'DIGIT SUPPORT');
INSERT INTO public.org_unit VALUES (805, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1198]', 'VGMIDT Administrasjon', '195', '194', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/195', 'VGMIDT ADM');
INSERT INTO public.org_unit VALUES (806, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1085]', 'DIGIT Fagtjenester', '47', '38', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/47', 'DIGIT FAGTJ');
INSERT INTO public.org_unit VALUES (807, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1228]', 'VGMIDT Realfag', '204', '194', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/204', 'VGMIDT REAL');
INSERT INTO public.org_unit VALUES (808, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1312]', 'VGBADE Administrasjon', '205', '198', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/205', 'VGBADE ADMIN');
INSERT INTO public.org_unit VALUES (809, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1108]', 'DIGIT Arbeidsflate', '1163', '38', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/1163', 'DIGIT ARBFL');
INSERT INTO public.org_unit VALUES (810, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1001]', 'Vår fylkeskommune', '1', '1', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/1', 'VFK');
INSERT INTO public.org_unit VALUES (811, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1350]', 'VGBADE Tekno', '218', '198', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/218', 'VGBADE TEKNO');
INSERT INTO public.org_unit VALUES (812, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1027]', 'DIGIT Digitaliseringsavdeling', '36', '5', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/36', 'DIGIT');
INSERT INTO public.org_unit VALUES (813, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1382]', 'INFRA Samferdsel', '8', '1', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/8', 'INFRA');
INSERT INTO public.org_unit VALUES (814, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1182]', 'KOMP Fag- og yrkesopplæring', '161', '151', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/161', 'KOMP FYOPPL');
INSERT INTO public.org_unit VALUES (815, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1123]', 'KOMP Utdanning og kompetanse', '6', '1', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/6', 'KOMP');
INSERT INTO public.org_unit VALUES (816, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1017]', 'OKO Regnskapsseksjon', '30', '26', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/30', 'OKO REGN');
INSERT INTO public.org_unit VALUES (817, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1417]', 'INFRA Mobilitetsseksjon', '93', '85', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/93', 'INFRA MOBILITET');
INSERT INTO public.org_unit VALUES (818, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1113]', 'DIGIT Tjenesteforvaltning', '40', '36', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/40', 'DIGIT TJFORV');
INSERT INTO public.org_unit VALUES (819, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1383]', 'INFRA Fagavdeling', '84', '8', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/84', 'INFRA FAGAVD');
INSERT INTO public.org_unit VALUES (820, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1002]', 'FAK Finans og administrasjon', '5', '1', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/5', 'FAK');
INSERT INTO public.org_unit VALUES (821, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1270]', 'VGMIDT Språk/Økonomi', '207', '194', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/207', 'VGMIDT SPROK');
INSERT INTO public.org_unit VALUES (822, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1080]', 'DIGIT Basistjenester', '46', '38', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/46', 'DIGIT BASIS');
INSERT INTO public.org_unit VALUES (823, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1078]', 'DIGIT Teknologiseksjon', '38', '36', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/38', 'DIGIT TEKN');
INSERT INTO public.org_unit VALUES (824, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1125]', 'KOMP Forvaltningsutvikling', '150', '6', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/150', 'KOMP FORVUTV');
INSERT INTO public.org_unit VALUES (825, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1005]', 'OKO Økonomiavdeling', '26', '5', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/26', 'OKO');
INSERT INTO public.org_unit VALUES (826, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1095]', 'DIGIT Plattform og Kommunikasjon', '48', '38', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/48', 'DIGIT KOMM');
INSERT INTO public.org_unit VALUES (827, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1007]', 'OKO Budsjett- og finansseksjon', '27', '26', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/27', 'OKO BUDFIN');
INSERT INTO public.org_unit VALUES (828, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1388]', 'INFRA Vei- og geofag', '89', '84', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/89', 'INFRA VEIGEO');
INSERT INTO public.org_unit VALUES (829, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1145]', 'KOMP Statistikk, analyse, system og administrativ støtte', '157', '150', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/157', 'KOMP ANALYSE');
INSERT INTO public.org_unit VALUES (830, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1064]', 'DIGIT Lokasjonssupport sone 2', '1120', '50', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/1120', 'DIGIT LOKSONE2');
INSERT INTO public.org_unit VALUES (831, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1192]', 'VGMIDT Midtbyen videregående skole', '194', '153', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/194', 'VGMIDT');
INSERT INTO public.org_unit VALUES (832, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1307]', 'VGBADE Badeland videregående skole', '198', '153', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/198', 'VGBADE');
INSERT INTO public.org_unit VALUES (833, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1049]', 'DIGIT Lokasjonssupport sone 1', '1119', '50', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/1119', 'DIGIT LOKSONE1');
INSERT INTO public.org_unit VALUES (834, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1335]', 'VGBADE Entreprenørskap', '211', '198', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/211', 'VGBADE ENTRE');
INSERT INTO public.org_unit VALUES (835, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1405]', 'INFRA Fremtidens transporter', '92', '85', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/92', 'INFRA FREMTRA');
INSERT INTO public.org_unit VALUES (836, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1159]', 'KOMP Kompetanseutvikling', '151', '6', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/151', 'KOMP KOMPUTV');
INSERT INTO public.org_unit VALUES (837, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1031]', 'DIGIT Serviceseksjon', '37', '36', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/37', 'DIGIT SERVSEK');
INSERT INTO public.org_unit VALUES (838, '[https://beta.felleskomponent.no/administrasjon/personal/personalressurs/ansattnummer/1191]', 'KOMP Område sørvest', '153', '6', 'https://beta.felleskomponent.no/administrasjon/organisasjon/organisasjonselement/organisasjonsid/153', 'KOMP SORVEST');
INSERT INTO public.org_unit_children_ref VALUES (803, '92');
INSERT INTO public.org_unit_children_ref VALUES (803, '93');
INSERT INTO public.org_unit_children_ref VALUES (804, '1178');
INSERT INTO public.org_unit_children_ref VALUES (804, '1119');
INSERT INTO public.org_unit_children_ref VALUES (804, '1120');
INSERT INTO public.org_unit_children_ref VALUES (810, '5');
INSERT INTO public.org_unit_children_ref VALUES (810, '6');
INSERT INTO public.org_unit_children_ref VALUES (810, '8');
INSERT INTO public.org_unit_children_ref VALUES (812, '37');
INSERT INTO public.org_unit_children_ref VALUES (812, '38');
INSERT INTO public.org_unit_children_ref VALUES (812, '40');
INSERT INTO public.org_unit_children_ref VALUES (813, '84');
INSERT INTO public.org_unit_children_ref VALUES (813, '85');
INSERT INTO public.org_unit_children_ref VALUES (815, '150');
INSERT INTO public.org_unit_children_ref VALUES (815, '151');
INSERT INTO public.org_unit_children_ref VALUES (815, '153');
INSERT INTO public.org_unit_children_ref VALUES (816, '35');
INSERT INTO public.org_unit_children_ref VALUES (819, '89');
INSERT INTO public.org_unit_children_ref VALUES (820, '26');
INSERT INTO public.org_unit_children_ref VALUES (820, '36');
INSERT INTO public.org_unit_children_ref VALUES (823, '46');
INSERT INTO public.org_unit_children_ref VALUES (823, '47');
INSERT INTO public.org_unit_children_ref VALUES (823, '48');
INSERT INTO public.org_unit_children_ref VALUES (823, '1163');
INSERT INTO public.org_unit_children_ref VALUES (824, '157');
INSERT INTO public.org_unit_children_ref VALUES (825, '27');
INSERT INTO public.org_unit_children_ref VALUES (825, '30');
INSERT INTO public.org_unit_children_ref VALUES (831, '195');
INSERT INTO public.org_unit_children_ref VALUES (831, '204');
INSERT INTO public.org_unit_children_ref VALUES (831, '207');
INSERT INTO public.org_unit_children_ref VALUES (832, '205');
INSERT INTO public.org_unit_children_ref VALUES (832, '211');
INSERT INTO public.org_unit_children_ref VALUES (832, '218');
INSERT INTO public.org_unit_children_ref VALUES (836, '161');
INSERT INTO public.org_unit_children_ref VALUES (837, '50');
INSERT INTO public.org_unit_children_ref VALUES (838, '194');
INSERT INTO public.org_unit_children_ref VALUES (838, '198');
