apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-orgunit-catalog
  app.kubernetes.io/instance: fint-kontroll-orgunit-catalog_vlfk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: vlfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "vlfk.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "https://role-catalog.vigoiks.no/vigo/kontroll/user"
      - op: replace
        path: "/spec/env/1/value"
        value: "vlfk.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vlfk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "vlfk-no.kontroll.*"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/vlfk-no/api/orgunits"
      - op: replace
        path: "/spec/url/hostname"
        value: "kontroll.novari.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/vlfk-no"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/vlfk-no/actuator/prometheus"
    target:
      kind: Application
      name: fint-kontroll-orgunit-catalog


